#!/bin/sh
set -eu
base="/lib/modules/$(uname -r)"
grep -q "^nf_log_common " /proc/modules || insmod "$base/nf_log_common.ko"
grep -q "^nf_log_ipv4 " /proc/modules || insmod "$base/nf_log_ipv4.ko"
grep -q "^nf_log_ipv6 " /proc/modules || insmod "$base/nf_log_ipv6.ko"
grep -q "^nf_nat " /proc/modules || insmod "$base/nf_nat.ko"
grep -q "^nf_tables " /proc/modules || insmod "$base/nf_tables.ko"
grep -q "^nf_tables_set " /proc/modules || insmod "$base/nf_tables_set.ko"
grep -q "^nft_chain_nat " /proc/modules || insmod "$base/nft_chain_nat.ko"
grep -q "^nft_counter " /proc/modules || insmod "$base/nft_counter.ko"
grep -q "^nft_ct " /proc/modules || insmod "$base/nft_ct.ko"
grep -q "^nft_fib " /proc/modules || insmod "$base/nft_fib.ko"
grep -q "^nft_fib_ipv4 " /proc/modules || insmod "$base/nft_fib_ipv4.ko"
grep -q "^nft_fib_ipv6 " /proc/modules || insmod "$base/nft_fib_ipv6.ko"
grep -q "^nft_flow_offload " /proc/modules || insmod "$base/nft_flow_offload.ko"
grep -q "^nft_hash " /proc/modules || insmod "$base/nft_hash.ko"
grep -q "^nft_limit " /proc/modules || insmod "$base/nft_limit.ko"
grep -q "^nft_log " /proc/modules || insmod "$base/nft_log.ko"
grep -q "^nft_masq " /proc/modules || insmod "$base/nft_masq.ko"
grep -q "^nft_nat " /proc/modules || insmod "$base/nft_nat.ko"
grep -q "^nft_numgen " /proc/modules || insmod "$base/nft_numgen.ko"
grep -q "^nft_quota " /proc/modules || insmod "$base/nft_quota.ko"
grep -q "^nft_queue " /proc/modules || insmod "$base/nft_queue.ko"
grep -q "^nft_redir " /proc/modules || insmod "$base/nft_redir.ko"
grep -q "^nft_reject " /proc/modules || insmod "$base/nft_reject.ko"
grep -q "^nf_flow_table_inet " /proc/modules || insmod "$base/nf_flow_table_inet.ko"
grep -q "^nf_flow_table_ipv4 " /proc/modules || insmod "$base/nf_flow_table_ipv4.ko"
grep -q "^nf_flow_table_ipv6 " /proc/modules || insmod "$base/nf_flow_table_ipv6.ko"
grep -q "^nft_fib_inet " /proc/modules || insmod "$base/nft_fib_inet.ko"
grep -q "^nf_reject_ipv4 " /proc/modules || insmod "$base/nf_reject_ipv4.ko"
grep -q "^nf_reject_ipv6 " /proc/modules || insmod "$base/nf_reject_ipv6.ko"
grep -q "^nft_reject_inet " /proc/modules || insmod "$base/nft_reject_inet.ko"
grep -q "^nft_reject_ipv4 " /proc/modules || insmod "$base/nft_reject_ipv4.ko"
grep -q "^nft_reject_ipv6 " /proc/modules || insmod "$base/nft_reject_ipv6.ko"
