#!/bin/sh /etc/rc.common
START=99
start() {
    for arg in $(cat /proc/cmdline); do
        case "$arg" in be7000_usb_dir=*) directory=${arg#*=};; esac
    done
    case "${directory:-}" in ''|*[!a-zA-Z0-9._-]*|.|..) return;; esac
    rm -f "/mnt/usb/$directory/boot/boot-pending"
}
