#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-only
# Default to flowtable acceleration; preserve explicit user choices.
set -e

uci -q get 'firewall.@defaults[0]' >/dev/null || exit 0
for option in flow_offloading flow_offloading_hw; do
	if uci -q get "firewall.@defaults[0].$option" >/dev/null; then
		exit 0
	fi
done

uci set 'firewall.@defaults[0].flow_offloading=1'
uci set 'firewall.@defaults[0].flow_offloading_hw=1'
uci commit firewall
