#!/bin/sh
. /etc/openwrt_release
mkdir -p /etc/apk/repositories.d
printf '%s\n' \
    "https://openwrt.quarx2k.dev/packages/$DISTRIB_REVISION/qualcommbe/ipq95xx/packages.adb" \
    'https://openwrt.quarx2k.dev/packages/common/aarch64_cortex-a53/packages.adb' \
    >/etc/apk/repositories.d/be7000.list
exit 0
