#!/bin/sh /etc/rc.common
START=19
STOP=18

start() {
    sh /usr/lib/be7000/acceleration.sh > /tmp/be7000-acceleration.log 2>&1
    local status=$?
    logger -t be7000-acceleration -f /tmp/be7000-acceleration.log
    return "$status"
}

stop() {
    # Stop creating flows; retain Ethernet drivers and existing interfaces.
    [ ! -d /sys/module/qca_nss_eip_ipsec ] || rmmod qca_nss_eip_ipsec
    [ ! -d /sys/module/qca_nss_nsm ] || rmmod qca_nss_nsm
    [ ! -d /sys/module/ecm_wifi_plugin ] || rmmod ecm_wifi_plugin
    [ ! -d /sys/module/ecm ] || rmmod ecm
}
